import { Histogram, PieChart, Tickets } from '@element-plus/icons-vue'
import type { ReportDefinition } from './report.types'

export const REPORTS: ReportDefinition[] = [
    {
        code: 'purposes',
        kind: 'purposes',
        title: 'Отчет по названию',
        listTitle: 'Отчет по названию',
        description: 'Показывает расходы и доходы сгруппированные по названию.',
        firstColumnLabel: 'Название',
        emptyTitle: '[Не назначенный]',
        icon: Tickets,
    },
    {
        code: 'income_expense',
        kind: 'income_expense',
        title: 'Приходы и Расходы',
        listTitle: 'Приходы и Расходы',
        description: 'Показывает приходы и расходы сгруппированные по месяцам.',
        firstColumnLabel: 'Дата',
        emptyTitle: 'Без периода',
        icon: Histogram,
    },
    {
        code: 'categories',
        kind: 'categories',
        title: 'Отчет по категориям',
        listTitle: 'Отчет по категориям',
        description: 'Показывает расходы и доходы сгруппированные по категориям.',
        firstColumnLabel: 'Категория',
        emptyTitle: 'Без категории',
        icon: PieChart,
    },
    {
        code: 'projects',
        kind: 'projects',
        title: 'Отчет по проектам',
        listTitle: 'Отчет по проектам',
        description: 'Показывает расходы и доходы сгруппированные по проектам.',
        firstColumnLabel: 'Проект',
        emptyTitle: 'Без проекта',
        icon: PieChart,
    },
    {
        code: 'payments',
        title: 'Отчет по платежам',
        listTitle: 'Отчет по платежам',
        description: 'Показывает список платежей за определенный период.',
        firstColumnLabel: 'Дата',
        emptyTitle: 'Без названия',
        icon: Tickets,
    },
]

export const PERIOD_OPTIONS = [
    { label: 'Весь период', value: 'all_period' },
    { label: 'Все до сегодня', value: 'all_to_today' },
    { label: 'За месяц до сегодня', value: 'month_to_today' },
    { label: 'За год до сегодня', value: 'year_to_today' },
    { label: 'Сегодня', value: 'today' },
    { label: 'Вчера', value: 'yesterday' },
    { label: 'Текущий месяц', value: 'current_month' },
    { label: 'Текущий год', value: 'current_year' },
    { label: 'Прошедший месяц', value: 'last_month' },
    { label: 'Прошедший год', value: 'last_year' },
    { label: 'За последние 30 дней', value: 'last_30_days' },
    { label: 'За последние 3 месяца', value: 'last_3_months' },
    { label: 'За последние 12 месяцев', value: 'last_12_months' },
    { label: 'Следующие 30 дней', value: 'next_30_days' },
    { label: 'Следующие 3 месяца', value: 'next_3_months' },
    { label: 'Установить свои даты...', value: 'custom' },
]

export const METHOD_OPTIONS = [
    { label: 'Кассовый метод', value: 'cashmethod' },
    { label: 'Метод начисления', value: 'accrualmethod' },
]

export const PROPERTY_LABELS: Record<string, string> = {
    id: 'ID',
    payment_id: 'ID платежа',
    purpose_id: 'ID названия',
    category_id: 'ID категории',
    project_id: 'ID проекта',
    account_id: 'ID счета',
    to_account_id: 'ID счета назначения',
    title: 'Название',
    payment_date: 'Дата',
    date_range: 'Период',
    account_title: 'Счет',
    to_account_title: 'Счет назначения',
    category_title: 'Категория',
    project_title: 'Проект',
    type: 'Тип',
    kind: 'Вид',
    note: 'Примечание',
    amount: 'Сумма',
    amount_formatted: 'Сумма',
    total_amount_formatted: 'Итого',
    income_formatted: 'Приход',
    total_income_formatted: 'Приход',
    expense_formatted: 'Расход',
    total_expense_formatted: 'Расход',
    transfer_formatted: 'Перевод',
    payments_count: 'Количество платежей',
    money_limit: 'Лимит',
    status: 'Статус',
    parent_id: 'Родитель',
    number: 'Номер',
    guid: 'GUID',
    tag: 'Тег',
}

export const HIDDEN_PROPERTY_KEYS = new Set([
    'children',
    'amount',
    'income',
    'expense',
    'transfer',
    'total',
    'total_formatted',
])
